# TRACE|DEBUG|INFO|WARN|ERROR
logging:
  level:
    org.springframework: WARN
    com.anandchakru.app: WARN
    org.hibernate: WARN
    root: WARN
  file: cifi3.log
spring: 
  application: 
    name: cifi3	
  main: 
    banner-mode: "off"
  datasource: 
    url: jdbc:mysql://localhost:3306/cifi3?useSSL=false&allowPublicKeyRetrieval=true
    username: cifi3prod
    password: cifi3prod
  jpa: 
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  data:
    rest:
      basePath: /repo
server:
  port: ${port:9090}
cifi: 
  name: Cifi3
  faults:
    UNXPTD_ERR: An Unexpected Error occurred.
    INVLD_OPRTN: Invalid Operation.
    INVLD_NODE_OR_APP: Invalid App or Node.