# TRACE|DEBUG|INFO|WARN|ERROR
logging:
  level:
    org.springframework: OFF
    com.anandchakru.app: DEBUG
    org.hibernate.type: TRACE
    org.hibernate: WARN
    root: OFF
  file: cifi3-local.log
spring: 
  datasource: 
    url: jdbc:mysql://localhost:3306/cifi3?useSSL=false&allowPublicKeyRetrieval=true
    username: tester
    password: tester
  jpa:
    show-sql: true