# TRACE|DEBUG|INFO|WARN|ERROR
logging:
  level:
    org.springframework: OFF
    com.anandchakru.app: OFF
    org.hibernate: DEBUG
    root: OFF
  file: cifi3.log
spring: 
  datasource: 
    url: jdbc:mysql://localhost:3306/cifi3?useSSL=false&allowPublicKeyRetrieval=true
    username: tester
    password: tester
cifi: 
  name: Cifi3