logging:
  level:
    org.hibernate.type: OFF
    org.hibernate: OFF
    root: OFF
  file: cifi3-test.log
spring: 
  datasource: 
    url: jdbc:h2:mem:cifi3
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa: 
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  h2: 
    console: 
      enabled: true
      path: /h2c